// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	healthz "ip_geo/internal/handler/healthz"
	"ip_geo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IpRateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/ip",
					Handler: GetIpGeoHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(5000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: healthz.HealthzHandler(serverCtx),
			},
		},
		rest.WithTimeout(100*time.Millisecond),
	)
}
